# Generated by Django 5.2.17 on 2026-09-12 08:40

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "This value must contain a non-whitespace character."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "This value must contain a non-whitespace character."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\S", "This value must contain a non-whitespace character."
                            )
                        ],
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="albums",
                        to="catalog.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["-release_year", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "track_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ]
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="catalog.album",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="catalog.song",
                    ),
                ),
            ],
            options={
                "ordering": ["track_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="songs",
            field=models.ManyToManyField(
                related_name="albums", through="catalog.AlbumTrack", to="catalog.song"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.CheckConstraint(
                condition=models.Q(("track_number__gte", 1), ("track_number__lte", 32767)),
                name="track_number_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                fields=("album", "track_number"),
                name="album_unique_track_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(fields=("album", "song"), name="album_unique_song"),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(
                condition=models.Q(("release_year__gte", 1), ("release_year__lte", 9999)),
                name="album_valid_release_year",
            ),
        ),
    ]
